version: "3.3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB:my_suavi
      - POSTGRES_USER:emme
      - POSTGRES_PASSWORD:m4nd4r1n
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data